Feature - Weather Gifs Website
carlosveigadev/weather-by-gifs pull request #1
Opened 2020-12-12 19:16 UTC by wrakc

- Install webpack and tailwind;
- Add main HTML files;
- Create index.js file with main functions;
- Add function to fetch weather from API;
- Add function to manipulate data and show in the DOM;
- Add function to fetch Gifs;
- Add function to manipulate the gifs and show them in the DOM;
- Add toggle button to change from Celsius to Fahrenheit;
- Add Readme.

2020-12-12 20:32 UTC, mosaaleb requested changes
#### Changes required

Well done @wrakc :clap:. You have handled most of the requirements :100:. Yet there are other requirements need to be handled before moving on.

- [ ] **[OPTIONAL]** Let's add a  ‘loading’ component that displays from the time the form is submitted until the information comes back from the API. This will improve the experience of your app visitors.

- [ ] **[OPTIONAL]** The page takes a few seconds before applying the styles. This issue comes from that the browser every time loads your app takes a very long time processing through your compiled final CSS file which contains all the styles that come from tailwind (around 3MB). To fix this issue you can use `purgecss` to remove all the un-used styles from the final build. Take a look at how to [optimize](https://tailwindcss.com/docs/optimizing-for-production) for production.


Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

2020-12-12 20:32 UTC, mosaaleb commented on src/modules/changeTemperature.js
> +function changeTemperature(data) {
- [ ] It uses ES6 syntax
![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/es6_requirement.png). 

Let's make sure to convert all the functions to arrow function syntax.

2020-12-12 20:32 UTC, mosaaleb commented on src/modules/checkUvIndex.js
> +function checkUvIndex(index) {
- [ ] let's replace it with arrow function syntax

2020-12-12 20:32 UTC, mosaaleb commented on dist/index.html
> +    <link href="./assets/css/tailwind.css" rel="stylesheet">
- [ ] There is a console error coming from this line. I believe that you already installed tailwind using postcss as instructed [here](https://tailwindcss.com/docs/installation#installing-tailwind-css-as-a-post-css-plugin)? If that's right, we don't need ths line. PostCSS already takes care of compiling tailwind styles.

2020-12-15 01:39 UTC, wrakc commented
Hi @mosaaleb,
Thanks for the review. 
I implemented the improvements as suggested.

2020-12-15 01:55 UTC, christianotieno approved these changes
### Milestone Approved 🍾 
Hello @wrakc 👋 
 ##
This feature branch has met all the requirements needed for approval. 👏 
Congratulations on the hard work done on this project. Good job 👍 
I will go ahead and mark this as complete. Good luck with the next tasks 🥇 
##
### Happy coding 💻 
#### Christian Otieno (TSE)

2020-12-15 02:33 UTC, merged